### ISSUE TITLE
No Outputs in the respective cassandra tables!!!

### ISSUE THREAD

**Issue by mkanchwala** [killrweather/killrweather#11]
I am new to this thing and am trying to setup this app successfully on my linux environment, But I am not able to see the Output in the database.

Please find the Logs for the respective APPs : 

1) app/run : 
/killrweather$ sbt 
[info] Loading project definition from /home/mkanchwala/killrweather/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-git:0.6.2 -> 0.6.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to KillrWeather.com (in build file:/home/mkanchwala/killrweather/)
[SBT] mkanchwala@mkanchwala::root> app/run
[info] Running com.datastax.killrweather.KillrWeatherApp 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/mkanchwala/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/mkanchwala/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.0.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
02/16/15 06:47:19 INFO [run-main-0] com.datastax.killrweather.WeatherSettings: Starting up with spark master 'local[*]' cassandra hosts '127.0.0.1'
ZooKeeperServer isRunning: true
ZooKeeper Client connected.
Starting the Kafka server at 127.0.1.1:2181
02/16/15 06:47:27 WARN [KillrWeather-akka.actor.default-dispatcher-5] org.apache.spark.util.Utils: Your hostname, mkanchwala resolves to a loopback address: 127.0.1.1; using 192.168.117.131 instead (on interface eth0)
02/16/15 06:47:27 WARN [KillrWeather-akka.actor.default-dispatcher-5] org.apache.spark.util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
02/16/15 06:47:33 INFO [KillrWeather-akka.actor.default-dispatcher-2] com.datastax.killrweather.NodeGuardian: Starting at akka.tcp://KillrWeather@127.0.1.1:2550
02/16/15 06:47:34 INFO [KillrWeather-akka.actor.default-dispatcher-18] com.datastax.killrweather.NodeGuardian: Node is transitioning from 'uninitialized' to 'initialized'

2) clients/run :  DataFeedAPP 

sbt
[info] Loading project definition from /home/mkanchwala/killrweather/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-git:0.6.2 -> 0.6.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to KillrWeather.com (in build file:/home/mkanchwala/killrweather/)
[SBT] mkanchwala@mkanchwala::root> clients/run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] com.datastax.killrweather.DataFeedApp
 [2] com.datastax.killrweather.KillrWeatherClientApp

Enter number: 1

[info] Running com.datastax.killrweather.DataFeedApp 
[INFO] [2015-02-16 06:48:51,659] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2015-02-16 06:48:52,097] [Remoting]: Starting remoting
[INFO] [2015-02-16 06:48:52,438] [Remoting]: Remoting started; listening on addresses :[akka.tcp://KillrWeather@127.0.1.1:47862]
[INFO] [2015-02-16 06:48:52,480] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Starting up...
[INFO] [2015-02-16 06:48:52,728] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [2015-02-16 06:48:52,729] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Started up successfully
[INFO] [2015-02-16 06:48:52,761] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Metrics will be retreived from MBeans, and may be incorrect on some platforms. To increase metric accuracy add the 'sigar.jar' to the classpath and the appropriate platform-specific native libary to 'java.library.path'. Reason: java.lang.ClassNotFoundException: org.hyperic.sigar.Sigar
[INFO] [2015-02-16 06:48:52,771] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - No seed-nodes configured, manual cluster join required
[INFO] [2015-02-16 06:48:52,795] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Metrics collection has started successfully
[INFO] [2015-02-16 06:48:52,851] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Node [akka.tcp://KillrWeather@127.0.1.1:47862] is JOINING, roles []
[INFO] [2015-02-16 06:48:52,895] [com.datastax.killrweather.AutomaticDataFeedActor]: Starting data file ingestion on akka.tcp://KillrWeather@127.0.1.1:47862.
[INFO] [2015-02-16 06:48:53,512] [akka.http.HttpManager]: Bound to localhost/127.0.0.1:8080
[INFO] [2015-02-16 06:48:53,716] [com.datastax.killrweather.DynamicDataFeedActor]: Connected to [/127.0.0.1:8080] with [akka.stream.impl.ActorProcessor@52f16502]
[INFO] [2015-02-16 06:48:53,788] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:47862] - Leader is moving node [akka.tcp://KillrWeather@127.0.1.1:47862] to [Up]
[INFO] [2015-02-16 06:48:57,942] [com.datastax.killrweather.FileFeedActor]: Ingesting /home/mkanchwala/killrweather/data/load/ny-sf-2008.csv.gz
[DEBUG] [2015-02-16 06:48:59,990] [com.datastax.killrweather.FileFeedActor]: Sending '724940:23234,2008,01,01,00,11.7,-0.6,1023.8,50,7.2,2,0.0,0.0'
[DEBUG] [2015-02-16 06:48:59,991] [com.datastax.killrweather.FileFeedActor]: Sending '724940:23234,2008,01,01,01,10.6,3.3,1023.5,100,4.1,4,0.0,0.0'
[DEBUG] [2015-02-16 06:48:59,994] [com.datastax.killrweather.FileFeedActor]: Sending '724940:23234,2008,01,01,02,10.6,1.7,1023.6,110,4.6,4,0.0,0.0'
.................

3) KillrWeatherClientAPP: 
clients/run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] com.datastax.killrweather.DataFeedApp
 [2] com.datastax.killrweather.KillrWeatherClientApp

Enter number: 2

[info] Running com.datastax.killrweather.KillrWeatherClientApp 
[INFO] [2015-02-16 06:51:00,246] [akka.event.slf4j.Slf4jLogger]: Slf4jLogger started
[INFO] [2015-02-16 06:51:01,108] [Remoting]: Starting remoting
[INFO] [2015-02-16 06:51:01,694] [Remoting]: Remoting started; listening on addresses :[akka.tcp://KillrWeather@127.0.1.1:39026]
[INFO] [2015-02-16 06:51:01,769] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Starting up...
[INFO] [2015-02-16 06:51:02,097] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Registered cluster JMX MBean [akka:type=Cluster]
[INFO] [2015-02-16 06:51:02,099] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Started up successfully
[INFO] [2015-02-16 06:51:02,157] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Metrics will be retreived from MBeans, and may be incorrect on some platforms. To increase metric accuracy add the 'sigar.jar' to the classpath and the appropriate platform-specific native libary to 'java.library.path'. Reason: java.lang.ClassNotFoundException: org.hyperic.sigar.Sigar
[INFO] [2015-02-16 06:51:02,185] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Metrics collection has started successfully
[INFO] [2015-02-16 06:51:02,205] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - No seed-nodes configured, manual cluster join required
[INFO] [2015-02-16 06:51:02,339] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Node [akka.tcp://KillrWeather@127.0.1.1:39026] is JOINING, roles []
[INFO] [2015-02-16 06:51:02,383] [com.datastax.killrweather.WeatherApiQueries]: Starting.
[INFO] [2015-02-16 06:51:03,146] [Cluster(akka://KillrWeather)]: Cluster Node [akka.tcp://KillrWeather@127.0.1.1:39026] - Leader is moving node [akka.tcp://KillrWeather@127.0.1.1:39026] to [Up]
[INFO] [2015-02-16 06:51:06,355] [com.datastax.killrweather.WeatherApiQueries]: Requesting the current weather for weather station 724940:23234
[INFO] [2015-02-16 06:51:06,673] [com.datastax.killrweather.WeatherApiQueries]: Requesting annual precipitation for weather station 724940:23234 in year 2008
[INFO] [2015-02-16 06:51:06,688] [com.datastax.killrweather.WeatherApiQueries]: Requesting top-k Precipitation for weather station 724940:23234
[INFO] [2015-02-16 06:51:06,709] [com.datastax.killrweather.WeatherApiQueries]: Requesting the daily temperature aggregate for weather station 724940:23234
[INFO] [2015-02-16 06:51:06,724] [com.datastax.killrweather.WeatherApiQueries]: Requesting the high-low temperature aggregate for weather station 724940:23234
[INFO] [2015-02-16 06:51:06,739] [com.datastax.killrweather.WeatherApiQueries]: Requesting weather station 724940:23234
[INFO] [2015-02-16 06:51:08,610] [com.datastax.killrweather.WeatherApiQueries]: Requesting the current weather for weather station 722020:12839
[INFO] [2015-02-16 06:51:08,628] [com.datastax.killrweather.WeatherApiQueries]: Requesting annual precipitation for weather station 722020:12839 in year 2008
[INFO] [2015-02-16 06:51:08,631] [com.datastax.killrweather.WeatherApiQueries]: Requesting top-k Precipitation for weather station 722020:12839
[INFO] [2015-02-16 06:51:08,637] [com.datastax.killrweather.WeatherApiQueries]: Requesting the daily temperature aggregate for weather station 722020:12839
[INFO] [2015-02-16 06:51:08,642] [com.datastax.killrweather.WeatherApiQueries]: Requesting the high-low temperature aggregate for weather station 722020:12839
[INFO] [2015-02-16 06:51:08,651] [com.datastax.killrweather.WeatherApiQueries]: Requesting weather station 722020:12839
[INFO] [2015-02-16 06:51:10,444] [com.datastax.killrweather.WeatherApiQueries]: Requesting the current weather for weather station 722950:23174
[INFO] [2015-02-16 06:51:10,448] [com.datastax.killrweather.WeatherApiQueries]: Requesting annual precipitation for weather station 722950:23174 in year 2008
[INFO] [2015-02-16 06:51:10,453] [com.datastax.killrweather.WeatherApiQueries]: Requesting top-k Precipitation for weather station 722950:23174
[INFO] [2015-02-16 06:51:10,457] [com.datastax.killrweather.WeatherApiQueries]: Requesting the daily temperature aggregate for weather station 722950:23174
[INFO] [2015-02-16 06:51:10,462] [com.datastax.killrweather.WeatherApiQueries]: Requesting the high-low temperature aggregate for weather station 722950:23174
[INFO] [2015-02-16 06:51:10,466] [com.datastax.killrweather.WeatherApiQueries]: Requesting weather station 722950:23174
[INFO] [2015-02-16 06:51:12,266] [com.datastax.killrweather.WeatherApiQueries]: Requesting the current weather for weather station 725300:94846
[INFO] [2015-02-16 06:51:12,273] [com.datastax.killrweather.WeatherApiQueries]: Requesting annual precipitation for weather station 725300:94846 in year 2008
[INFO] [2015-02-16 06:51:12,279] [com.datastax.killrweather.WeatherApiQueries]: Requesting top-k Precipitation for weather station 725300:94846
[INFO] [2015-02-16 06:51:12,283] [com.datastax.killrweather.WeatherApiQueries]: Requesting the daily temperature aggregate for weather station 725300:94846
[INFO] [2015-02-16 06:51:12,284] [com.datastax.killrweather.WeatherApiQueries]: Requesting the high-low temperature aggregate for weather station 725300:94846
[INFO] [2015-02-16 06:51:12,289] [com.datastax.killrweather.WeatherApiQueries]: Requesting weather station 725300:94846
[ERROR] [2015-02-16 06:51:16,059] [akka.actor.OneForOneStrategy]: next on empty iterator
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39) ~[scala-library.jar:0.13.7]
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37) ~[scala-library.jar:0.13.7]
	at scala.collection.IterableLike$class.head(IterableLike.scala:91) ~[scala-library.jar:0.13.7]
	at scala.collection.AbstractIterable.head(Iterable.scala:54) ~[scala-library.jar:0.13.7]
	at com.datastax.killrweather.WeatherApiQueries.queries(KillrWeatherClientApp.scala:76) ~[classes/:na]
	at com.datastax.killrweather.WeatherApiQueries$$anonfun$receive$1.applyOrElse(KillrWeatherClientApp.scala:61) ~[classes/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.8.jar:na]
	at com.datastax.killrweather.WeatherApiQueries.aroundReceive(KillrWeatherClientApp.scala:37) ~[classes/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.10-2.3.8.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.10-2.3.8.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.10-2.3.8.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
[INFO] [2015-02-16 06:51:16,091] [com.datastax.killrweather.WeatherApiQueries]: Starting.
[INFO] [2015-02-16 06:51:16,145] [com.datastax.killrweather.WeatherApiQueries]: Requesting the current weather for weather station 724940:23234
[INFO] [2015-02-16 06:51:16,153] [com.datastax.killrweather.WeatherApiQueries]: Requesting annual precipitation for weather station 724940:23234 in year 2008
[INFO] [2015-02-16 06:51:16,156] [com.datastax.killrweather.WeatherApiQueries]: Requesting top-k Precipitation for weather station 724940:23234
[INFO] [2015-02-16 06:51:16,161] [com.datastax.killrweather.WeatherApiQueries]: Requesting the daily temperature aggregate for weather station 724940:23234
[INFO] [2015-02-16 06:51:16,167] [com.datastax.killrweather.WeatherApiQueries]: Requesting the high-low temperature aggregate for weather station 724940:23234
[INFO] [2015-02-16 06:51:16,173] [com.datastax.killrweather.WeatherApiQueries]: Requesting weather station 724940:23234

@helena @searler : Can you guys suggest me what am I doing wrong here?

Thanks

**Comment by helena** [comment]
You have Cassandra running locally correct?

**Comment by jcfrancisco17** [comment]
Yes, cassandra is running locally. I'm using cassandra 2.1.2. 

I got the KafkaStreamingJson2 example working. The data in that example reached Cassandra.

**Comment by helena** [comment]
and you ran:

cqlsh> source 'create-timeseries.cql';
    cqlsh> source 'load-timeseries.cql';

**Comment by helena** [comment]
Ok i can replicate this, I must have a regression from version upgrades.

**Comment by helena** [comment]
Resolved by latest commit, thanks for the heads up :)

**Comment by jcfrancisco17** [comment]
Thanks! Giving it another try. :)

**Comment by mkanchwala** [comment]
Thanks for the update @helena
