### ISSUE TITLE
Setup using wrong directory path

### ISSUE THREAD

**Issue by dsosnoski** [killrweather/killrweather#3]
Setup step 3 needs to be run in the ./data directory of the project, not the project root directory.

**Comment by helena** [comment]
@dsosnoski the README says:

Run the setup cql scripts to create the schema and populate the weather stations table. On the command line start a cqlsh shell:

cd /path/to/killrweather ~/apache-cassandra-{latest.version}/bin/cqlsh

You could run it in /data if you add cassandra_home/bin to you path, which I do, but if not you would need to run it in the cassandra_home/bin as the README shows.

Did I misunderstand you? Maybe you found something else that said to run in /killrweather/ ?

**Comment by helena** [comment]
Fixed, thanks.
