### ISSUE TITLE
cassandra connection error

### ISSUE THREAD

**Issue by matesio** [killrweather/killrweather#49]
[akka.actor.OneForOneStrategy]: Failed to open native connection to Cassandra at {127.0.1.1}:9042
akka.actor.ActorInitializationException: exception during creation
	
i have tried changing rpc_address:127.0.1.1 but all in vain , can you please suggest me what can i do?
Thanks

**Comment by paulczar** [comment]
set env variable `CASSANDRA_SEEDS=127.0.0.1` or whatever IP your cassandra is running on.
